(component
  (core type (;0;)
    (module)
  )
  (import "i1" (core module (;0;) (type 0)))
  (core module (;1;))
  (core module (;2;))
  (core module (;3;))
  (component (;1;)
    (type (;0;) (func (param "p" string)))
    (import "a" (func (;0;) (type 0)))
  )
  (export (;4;) "x" (core module 3))
)
